/**
 * THIS FILE IS GENERATED BY jsonrpcstub, DO NOT CHANGE IT!!!!!
 */

#ifndef _ABSTRACTWGSLIBSTUBSERVER_H_
#define _ABSTRACTWGSLIBSTUBSERVER_H_

#include <jsonrpc/rpc.h>

class AbstractWGSLibStubServer : public jsonrpc::AbstractServer<AbstractWGSLibStubServer>
{
    public:
        AbstractWGSLibStubServer(jsonrpc::AbstractServerConnector* conn) :
            jsonrpc::AbstractServer<AbstractWGSLibStubServer>(conn) 
        {
            this->bindAndAddMethod(new jsonrpc::Procedure("compute_variograms", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_ARRAY, "X_prop",jsonrpc::JSON_INTEGER,"Y_prop",jsonrpc::JSON_INTEGER,"Z_prop",jsonrpc::JSON_INTEGER,"dimensions",jsonrpc::JSON_ARRAY,"directions",jsonrpc::JSON_ARRAY,"grid_name",jsonrpc::JSON_STRING,"num_lags",jsonrpc::JSON_INTEGER,"props",jsonrpc::JSON_ARRAY,"props_name",jsonrpc::JSON_ARRAY,"props_selected",jsonrpc::JSON_ARRAY, NULL), &AbstractWGSLibStubServer::compute_variogramsI);
            this->bindAndAddNotification(new jsonrpc::Procedure("notifyServer", jsonrpc::PARAMS_BY_NAME,  NULL), &AbstractWGSLibStubServer::notifyServerI);

        }
        
        inline virtual void compute_variogramsI(const Json::Value& request, Json::Value& response) 
        {
            response = this->compute_variograms(request["X_prop"].asInt(), request["Y_prop"].asInt(), request["Z_prop"].asInt(), request["dimensions"], request["directions"], request["grid_name"].asString(), request["num_lags"].asInt(), request["props"], request["props_name"], request["props_selected"]);
        }

        inline virtual void notifyServerI(const Json::Value& request) 
        {
            this->notifyServer();
        }


        virtual Json::Value compute_variograms(const int& X_prop, const int& Y_prop, const int& Z_prop, const Json::Value& dimensions, const Json::Value& directions, const std::string& grid_name, const int& num_lags, const Json::Value& props, const Json::Value& props_name, const Json::Value& props_selected) = 0;
        virtual void notifyServer() = 0;

};
#endif //_ABSTRACTWGSLIBSTUBSERVER_H_
