/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_WGSLIBSTUBSERVER_H_
#define JSONRPC_CPP_STUB_WGSLIBSTUBSERVER_H_

#include <jsonrpccpp/server.h>

class WGSLibStubServer : public jsonrpc::AbstractServer<WGSLibStubServer>
{
    public:
        WGSLibStubServer(jsonrpc::AbstractServerConnector &conn) : jsonrpc::AbstractServer<WGSLibStubServer>(conn)
        {
            this->bindAndAddMethod(new jsonrpc::Procedure("compute_variograms", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_ARRAY, "X_prop",jsonrpc::JSON_INTEGER,"Y_prop",jsonrpc::JSON_INTEGER,"Z_prop",jsonrpc::JSON_INTEGER,"dimensions",jsonrpc::JSON_ARRAY,"directions",jsonrpc::JSON_ARRAY,"grid_name",jsonrpc::JSON_STRING,"num_lags",jsonrpc::JSON_INTEGER,"props",jsonrpc::JSON_ARRAY,"props_name",jsonrpc::JSON_ARRAY,"props_selected",jsonrpc::JSON_ARRAY, NULL), &WGSLibStubServer::compute_variogramsI);
            this->bindAndAddNotification(new jsonrpc::Procedure("notifyServer", jsonrpc::PARAMS_BY_POSITION,  NULL), &WGSLibStubServer::notifyServerI);
        }

        inline virtual void compute_variogramsI(const Json::Value &request, Json::Value &response)
        {
            response = this->compute_variograms(request["X_prop"].asInt(), request["Y_prop"].asInt(), request["Z_prop"].asInt(), request["dimensions"], request["directions"], request["grid_name"].asString(), request["num_lags"].asInt(), request["props"], request["props_name"], request["props_selected"]);
        }
        inline virtual void notifyServerI(const Json::Value &request)
        {
            this->notifyServer();
        }
        virtual Json::Value compute_variograms(const int& X_prop, const int& Y_prop, const int& Z_prop, const Json::Value& dimensions, const Json::Value& directions, const std::string& grid_name, const int& num_lags, const Json::Value& props, const Json::Value& props_name, const Json::Value& props_selected) = 0;
        virtual void notifyServer() = 0;
};

#endif //JSONRPC_CPP_WGSLIBSTUBSERVER_H_
